name: prestashop

services:
# mariaDB
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # contraseña root BD
      MYSQL_DATABASE: prestashop # nombre base de datos
      MYSQL_USER: prestashop_user # usuario
      MYSQL_PASSWORD: 1234 # contraseña

# prestashop
  ps:
    depends_on:
      - db # depende de la base de datos
    image: prestashop/prestashop
    ports:
      - "8000:80" # mapear al puerto 8000 del host
    restart: always
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop_user
      DB_PASSWD: 1234

volumes:
  db_data:
